all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host={{ hostvars[vm_tag_db_lb]['private_ip_address'] }};dbname=siwapp'
      username: '{{galera_db_user}}'
      password: '{{galera_db_user_pwd}}'
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host={{ hostvars[vm_tag_db_lb]['private_ip_address'] }};dbname=siwapp_test'
      username: '{{galera_db_user}}'
      password: '{{galera_db_user_pwd}}'
