---
- name: Create deployment instance connection
  scicore.guacamole.guacamole_connection:
    base_url: "{{ guac_url }}"
    auth_username: "{{ guac_user }}"
    auth_password: "{{ guac_pass }}"
    group_name: "{{ cco_username }}-{{ application_name }}"
    connection_name: "{{ ansible_hostname }}"
    protocol: ssh
    hostname: "{{ ansible_host }}"
    port: 22
    username: root
    password: "{{ cco_pass }}"

#- name: Add a new guacamole user
#  scicore.guacamole.guacamole_user:
#    base_url: "{{ guac_url }}"
#    auth_username: "{{ guac_user }}"
#    auth_password: "{{ guac_pass }}"
#    username: "{{ cco_username }}"
#    allowed_connections:
#      - "{{ ansible_hostname }}"
