---
- name: Create 'wheel' user group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user: name=siwapp groups=wheel append=yes state=present createhome=yes

# Tasks for configuring the application instances
- name: Create local hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Install EPEL release
  yum:
    name:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - libselinux-python
    state: latest

#- name: EPEL
# command: sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y


- name: Turn off SELinux
  selinux:
    state: disabled

# - name: Perform yum update for all packages
#   yum:
#     name: '*'
#     state: latest


- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Install packages with yum
  yum:
    name: git, httpd, php, php-mysql, php-xml, nginx, mysql
    state: present

- name: Retrieve HTML files from git
  git:
    repo: https://github.com/siwapp/siwapp-sf1.git
    dest: /var/www/html/
    clone: yes
    update: yes
    force: yes

- name: Create cache directory
  file:
    path: /var/www/html/cache
    state: directory
    mode: 0777

- name: Change file permissions
  file:
    path: /var/www/html/web/config.php
    mode: 0777

- name: Create uploads directory
  file:
    path: /var/www/html/web/uploads
    state: directory
    mode: 0777

- name: Change directory ownership to apache
  file:
    path: /var/www/html/
    state: directory
    owner: apache
    group: apache

- name: Copy pre_installer_code.php with lines removed
  template:
    src: pre_installer_code.php
    dest: /var/www/html/web/pre_installer_code.php

- name: Create modified httpd.conf file
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: Create modified layout.php file
  template:
    src: layout.php
    dest: /var/www/html/apps/siwapp/templates/layout.php

- name: Create modified databases.yml file
  template:
    src: databases.yml
    dest: /var/www/html/config/databases.yml
    mode: 0777

# is there a reason that the firefly script creates a
# config.php.bak file with sw_installed set to false?
# I'm not creating the .bak file here.
- name: Create modified config.php file
  template:
    src: config.php
    dest: /var/www/html/web/config.php

- name: Enable and start the httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Copy nginx conf file
  template:
    src: siwapp.conf
    dest: /etc/nginx/conf.d/siwapp.conf

- name: Enable and start the nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes