---

# # =========================================================
# #       PLAY -- Read in global variables
# # ---------------------------------------------------------

- name: Include deployment information
  hosts: all
  gather_facts: False
  vars:
    Name: {{ tags.Name }} 
    Instance Id: {{ instance_id }} 
    Region: {{ placement.region }} 
    Zone: {{ placement.availability_zone }} 
    Instance Type: {{  instance_type }}
    Public Ip: {{ public_ip_address }}
    Private Ip: {{ private_ip_address }}
    Tags: {{ tags }}
  
# =========================================================
#       PLAY -- Configure database tier
# ---------------------------------------------------------

- name: Configure instances in database tier
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: True

  pre_tasks:
  - name: Pause for all instances to be ready for configuration
    wait_for_connection:
      sleep: 5
      timeout: 300
    
  roles:
  - siwapp_db
